baseurl = "http://www.example.com"
title = "Dr. Bluebird"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 6
enableEmoji = true

disqusShortname = "yourdiscussshortname"

[markup.highlight]
noClasses = false

[params]
  author = "Panfeng Liang"
  info = "Research Statistician"
  description = "My personal website"
  keywords = "blog, statistics, consulting, personal"
  avatarurl = "images/avatar.png"
  faviconSVG = "images/logos/favicon.svg"
  math=true


  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false


   
[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Gitlab"
  icon = "fa-brands fa-gitlab fa-2x"
  weight = 2
  url = "https://github.com/bluebirdie"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/panfeng-liang-308201256/"


# Menu links
[[menu.main]]
  name = "CV"
  weight = 2
  url = "cv/"
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "Contact me"
  weight = 1
  url  = "contact/"

